version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_ENVIRONMENT=development
    depends_on:
      - backend
    networks:
      - ripple-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    networks:
      - ripple-network
    volumes:
      - ./backend/src:/app/src

networks:
  ripple-network:
    driver: bridge

volumes:
  ripple-data: