# Netlify Configuration for yoohoo.guru Platform
#
# Note: This is a Node.js/Next.js Turborepo monorepo (NOT Nx).
# Python dependencies have been moved to python-mcp-server/ subdirectory
# to prevent Netlify from auto-detecting and attempting to install them.
#
# Build Tool: Turborepo (turbo)
# Monorepo Structure: npm workspaces
# Package Manager: npm

[build]
  # Set base to the main app directory for the Next.js plugin to work correctly
  base = "apps/main"

  # Build command for Turborepo monorepo - builds the main app by default.
  # Using npm install (not npm ci) ensures proper workspace dependency resolution.
  # Note: Must install from root first to setup workspace, then build from app directory
  command = "cd ../.. && npm install && npx turbo run build --filter=@yoohooguru/main"

  # Publish directory for Next.js - handled automatically by @netlify/plugin-nextjs
  # The plugin knows to use .next directory when base is set to the app root

[build.environment]
  # Force Netlify to include devDependencies (TypeScript, ESLint, etc.)
  NODE_ENV = "development"
  NPM_FLAGS = "--include=dev"

  # Ensure consistent Node version (Use stable Node 20 LTS)
  NODE_VERSION = "20"

  # Enable Turborepo build caching
  TURBO_CACHE_DIR = ".turbo"

# Use the Nx skip build plugin to handle monorepo builds properly
[[plugins]]
  package = "netlify-plugin-nx-skip-build"

# Use the official Netlify Next.js runtime as secondary plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Recommended Deployment Architecture
# ------------------------------------
# Each app can be deployed separately for isolation and scalability.
# Frontend (Next.js apps) → Vercel or Netlify
# Backend (Express/Firebase APIs) → Railway or Cloud Run
#
# Example commands for alternate apps:
# - Angel app:
#     command = "npm install && npx turbo run build --filter=@yoohooguru/angel"
#     publish = "apps/angel/.next"
# - Coach app:
#     command = "npm install && npx turbo run build --filter=@yoohooguru/coach"
#     publish = "apps/coach/.next"
# - Heroes app:
#     command = "npm install && npx turbo run build --filter=@yoohooguru/heroes"
#     publish = "apps/heroes/.next"
# - Dashboard app:
#     command = "npm install && npx turbo run build --filter=@yoohooguru/dashboard"
#     publish = "apps/dashboard/.next"
#
# See docs/DEPLOYMENT.md for details.
