# Netlify Configuration for yoohoo.guru Platform
#
# Note: This is a Node.js/Next.js Turborepo monorepo
# Python dependencies have been moved to python-mcp-server/ subdirectory
# to prevent Netlify from auto-detecting and attempting to install them

[build]
  # CRITICAL FIX: Explicitly set base to the repository root to correctly resolve the 'publish' path for monorepos.
  base = "/"
  # Build command for Turborepo monorepo - builds the main app by default
  # Using npm install instead of npm ci to ensure proper workspace dependency resolution
  # npm install handles workspace devDependencies better than npm ci in some environments
  command = "npm install && npx turbo run build --filter=@yoohooguru/main"
  publish = "apps/main/.next"
  
[build.environment]
  # Use Node.js 20 LTS - Netlify will use the latest available Node 20.x version
  # Specifying just "20" ensures compatibility with Netlify's build image
  NODE_VERSION = "20"

# Next.js Runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# IMPORTANT: Recommended Deployment Architecture
# This repository is designed for deploying each app separately:
# - Frontend (Next.js apps): Deploy to Vercel (25 separate projects, one per app)
# - Backend (Node.js/Express): Deploy to Railway
# 
# If using Netlify, you should create separate Netlify projects for each app
# and configure the build command and publish directory accordingly.
# 
# Example build commands for different apps (npm ci for reproducible builds):
# - Main app: build="npm ci && npx turbo run build --filter=@yoohooguru/main", publish="apps/main/.next"
# - Angel app: build="npm ci && npx turbo run build --filter=@yoohooguru/angel", publish="apps/angel/.next"
# - Coach app: build="npm ci && npx turbo run build --filter=@yoohooguru/coach", publish="apps/coach/.next"
# - Heroes app: build="npm ci && npx turbo run build --filter=@yoohooguru/heroes", publish="apps/heroes/.next"
# - Dashboard app: build="npm ci && npx turbo run build --filter=@yoohooguru/dashboard", publish="apps/dashboard/.next"
# 
# See docs/DEPLOYMENT.md for complete deployment guide
