# Nixpacks configuration for yoohoo.guru monorepo
[variables]
NIXPACKS_NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"