# Nixpacks configuration for yoohoo.guru backend-only deployment
[phases.install]
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"