#!/bin/bash
# Vercel Environment Variables Setup Helper
# This script helps you set up environment variables for yoohooguru-main project

set -e

echo "🔧 Vercel Environment Variables Setup Helper"
echo "=============================================="
echo ""
echo "This script will help you configure environment variables for the yoohooguru-main project."
echo "You can either:"
echo "  1. Run the commands manually (recommended for security)"
echo "  2. Generate a script to run all at once"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Required Environment Variables:${NC}"
echo ""

echo "# =========================================="
echo "# API Configuration"
echo "# =========================================="
echo "npx vercel env add NEXT_PUBLIC_API_URL production preview development"
echo "# Enter value: https://api.yoohoo.guru"
echo ""

echo "# =========================================="
echo "# Firebase Configuration"
echo "# =========================================="
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_API_KEY production preview development"
echo "# Enter your Firebase API key"
echo ""
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production preview development"
echo "# Enter your Firebase auth domain (e.g., your-project.firebaseapp.com)"
echo ""
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID production preview development"
echo "# Enter your Firebase project ID"
echo ""
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production preview development"
echo "# Enter your Firebase storage bucket (e.g., your-project.appspot.com)"
echo ""
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production preview development"
echo "# Enter your Firebase messaging sender ID"
echo ""
echo "npx vercel env add NEXT_PUBLIC_FIREBASE_APP_ID production preview development"
echo "# Enter your Firebase app ID"
echo ""

echo "# =========================================="
echo "# NextAuth Configuration (CRITICAL - Keep Secret!)"
echo "# =========================================="
echo "# Generate a secret first: openssl rand -base64 32"
echo "npx vercel env add NEXTAUTH_SECRET production preview development"
echo "# Paste the generated secret"
echo ""
echo "npx vercel env add NEXTAUTH_URL production"
echo "# Enter value: https://www.yoohoo.guru"
echo ""

echo "# =========================================="
echo "# Cross-Subdomain Authentication (CRITICAL!)"
echo "# =========================================="
echo "npx vercel env add AUTH_COOKIE_DOMAIN production preview development"
echo "# Enter value: .yoohoo.guru"
echo "# NOTE: The leading dot (.) is CRITICAL for cross-subdomain auth!"
echo ""

echo "# =========================================="
echo "# Optional: Stripe Configuration"
echo "# =========================================="
echo "npx vercel env add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY production preview development"
echo "# Enter your Stripe publishable key (pk_live_... or pk_test_...)"
echo ""

echo "# =========================================="
echo "# Optional: Agora Video Configuration"
echo "# =========================================="
echo "npx vercel env add NEXT_PUBLIC_AGORA_APP_ID production preview development"
echo "# Enter your Agora app ID (if using video features)"
echo ""
echo "npx vercel env add NEXT_PUBLIC_AGORA_REGION production preview development"
echo "# Enter value: us (or your region)"
echo ""

echo "# =========================================="
echo "# Optional: Feature Flags"
echo "# =========================================="
echo "npx vercel env add FEATURE_HERO_GURUS production preview development"
echo "# Enter value: true"
echo ""
echo "npx vercel env add FEATURE_BACKGROUND_CHECKS production preview development"
echo "# Enter value: false"
echo ""

echo -e "${YELLOW}================================================${NC}"
echo -e "${YELLOW}Instructions:${NC}"
echo ""
echo "1. Copy the commands above"
echo "2. Run each command in your terminal"
echo "3. When prompted, enter the value for each variable"
echo "4. For multi-environment variables, the same value will be used across Production, Preview, and Development"
echo ""
echo -e "${GREEN}Alternative - Set via Vercel Dashboard:${NC}"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Navigate to yoohooguru-main → Settings → Environment Variables"
echo "3. Add each variable with the appropriate environments selected"
echo ""
echo -e "${YELLOW}Security Reminders:${NC}"
echo ""
echo "• NEVER commit secrets to git"
echo "• Generate a strong NEXTAUTH_SECRET: openssl rand -base64 32"
echo "• AUTH_COOKIE_DOMAIN must have leading dot: .yoohoo.guru"
echo "• Public keys (NEXT_PUBLIC_*) are safe to expose in client"
echo "• NEXTAUTH_SECRET must remain secret"
echo ""
echo "================================================"
echo ""
echo -e "${BLUE}After setting environment variables:${NC}"
echo "1. Trigger a new deployment: git push or 'npx vercel --prod'"
echo "2. Verify deployment succeeds"
echo "3. Run verification script: bash scripts/verify-vercel-setup.sh"
echo ""
